### ISSUE TITLE
Open file on macOS (Catalina)

### ISSUE THREAD

**Issue by daniellesent** [detsutut/shinyDBNet#1]
When I use the code as available from here and try to open an existing BN, no window to chose a file is opened. This seems a macOS issue.

**Comment by detsutut** [comment]
Hi Danielle,

I ran through it and it doesn't seem to be a macOS issue.
Existing BNs are uploaded using a fileInput element, which turned out to have some compatibility problems with non-standard browsers. 

My guess is that you're using RStudio's internal browser to run the app locally. In this case, you can solve the issue simply by switching from "Run in Window" to "Run External" in your RStudio configuration (see attachment).

Please let me know if this solves the issue for you.

![help](https://user-images.githubusercontent.com/15331758/86346924-e4831e00-bc5d-11ea-9081-fc2a0979d325.png)
